server:
  servlet:
    context-path: /api/read2/
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.com
    port: 465
    protocol: smtps
    username:
    password:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/read2}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    open-in-view: true

jwt:
  expiration: 1500
